### ISSUE TITLE
a Pet belongs_to one Owner but spec expects checkboxes to select multiple owners in the form for a new pet

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/sinatra-complex-forms-associations#22]
in `pets_controller_spec.rb` the capybara methods used are `check(@owner1.id)` and `expect(page.has_unchecked_field?(@owner2.id)).to eq(true)`.  This forces the student to use checkboxes in their pets/new.erb view.

from the solution branch:

``` ruby
<%Owner.all.each do |owner|%>
    <input type="checkbox" name="pet[owner_id]" id="<%= owner.name %>" value="<%=owner.id%>"><%=owner.name%></input>
  <%end%>
```

Since a pet can only have one owner, students use radio buttons and then get confused as to why the tests expect checkboxes.

`choose` I think is the capybara method that should be used, possibly some other changes.

**Comment by cernanb** [comment]
updated
