### ISSUE TITLE
Owner ID mismatch in Readme

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/sinatra-complex-forms-associations#24]
@owner = Owner.create(params["owner"])
# => #<Owner:0x007fdfcc96e430 id: 2, name: "Adele"> ***<- here the Owner's ID is listed as 2

@owner.pets
# => [#<Pet:0x007fb371bc22b8 id: 1, name: "Maddy", owner_id: 5>, #<Pet:0x007fb371bc1f98 id: 2, name: "Nona", owner_id: 5>] ***<- here the same owner (logical assumption from readme flow) is listed as having an ID of 5 instead of 2.

This may be minor, but eliminating small discrepancies can go a long way towards eliminating unnecessary confusion :)

**Comment by gooryalhamed** [comment]
That's right
