### ISSUE TITLE
View is pulling data directly from database in the README

### ISSUE THREAD

**Issue by scottibe** [learn-co-curriculum/sinatra-complex-forms-associations#27]
In a previous lesson we are taught that you should never pull data from the database in a view but rather, create a helper method in the controller and use that to access the data in the view. The code in this README seems to be doing exactly what were taught not to do. 

In the CREATING A NEW OWNER AND ASSOCIATING THEM WITH A NEW PET section the code to create dynamic checkboxes is as follows
<label>Choose an existing pet:</label>
 
  <br></br>
 
  <%Pet.all.each do |pet|%>
    <input type="checkbox" name="owner[pet_ids][]" id="<%=pet.id%>" value="<%=pet.id%>"><%=pet.name%></input>
  <%end%>

I believe Pet.all is pulling from the database. The same thing occurs later in the README in the:
EDITING OWNERS AND ASSOCIATED PETS section

Just wanted to let you know as it seems to be in conflict with earlier lessons. Thanks. -Scott

**Comment by sgharms** [comment]
It's an interesting point. I'd say that we're putting the thinnest of veneers over `Pet.all`, but I think your point is well made. If we wanted to change the query it's sensible to do that in the controller. Professionally speaking I'd kinda shrug on this one and you'll certainly see it done, but as a rule of thumb you're thinking in the right place.

Steven
