### ISSUE TITLE
Capybara checking for different fields on new and edit forms

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/sinatra-complex-forms-associations#31]
In the `pets_controller_spec`, Capybara is looking for owner checkboxes for the new action, but radio buttons for the edit action. Is this intentional? Shouldn't they be the same for consistency?

_new action_
```
    it "creates a new pet and associates an existing owner" do
      @owner1 = Owner.create(:name => "Cricky")
      @owner2 = Owner.create(:name => "Chris")
      visit '/pets/new'
      fill_in "pet_name", :with => "Michael"
      **check(@owner1.id)**
      click_button "Create Pet"
      @pet = Pet.last
      expect(@pet.name).to eq("Michael")
      expect(@pet.owner.name).to eq("Cricky")
    end
```
_edit action_
``` 
    it "edit's the pet's owner with an existing owner" do
      @adam = Owner.create(:name => "Adam")
      visit "/pets/#{@pet.id}/edit"
      **choose(@adam.id)**
      click_button "Update Pet"
      expect(Pet.last.owner.name).to eq("Adam")
    end
```

@aturkewi

**Comment by yehudamakarov** [comment]
Seemingly, but upon using radio buttons, the checkbox tests do not break.

**Comment by sgharms** [comment]
I think there's a subtle design idea here. Checkbox means "select of a free range from a population that's not been pre-constrained" while a radio means "select an option from a pre-constrained population." It's definitely a good question, but not a _bug_ per se. I applaud your reasoning here though.
