### ISSUE TITLE
ActiveRecord::Migrator doesn't exist in v5 

### ISSUE THREAD

**Issue by rishter** [learn-co-curriculum/sinatra-complex-forms-associations#41]
We should stay consistent with other ActiveRecord documentation and enforce version 4.2.5 in the `Gemfile`

**Comment by DanielSeehausen** [comment]
thank you @rishter @MinesJA 
currently, only waiting on new branch pr for the solution. there are a cacophony with solution <-- master right now, so @MinesJA is working on that and will submit.
