### ISSUE TITLE
Pet belongs to an 1 owner, etc.

### ISSUE THREAD

**Issue by BarbaraPruz** [learn-co-curriculum/sinatra-complex-forms-associations#43]
A few things I found complicated when I tried to get the tests to pass. Note: based on the description and owner code, I thought I had good understanding of the Pet requirements, so I coded and tested with shotgun and then ran the tests.
- pet belongs to a single owner and so for pet new/edit, user should be able to only select 1 owner (radio button vs checkbox) or create a new one.  Spec for pet new requires checkbox.
- similarly, I think the pet erbs and controller are sometimes using an [] for pet's owner but there is only 1 owner. (I'm not sure if I am mis-interpreting here)
- not sure if this will be addressed in another lesson but new owners can steal pets.  Shouldn't the pet list on the new owner form just be "un-owned" pets?
- not sure if critical for this small app but the views seems to sometimes access model (ex. erb will have Pet.all.each).   I thought best practice would be for controller to store the "all" for the erb to render.   Related to stealing pets, the controller could retrieve list of pets in need of owners, and then view would just render that list.
Going to walk my dog now.  Thanks!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#46.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
