### ISSUE TITLE
MVC violations + non-RESTful routing

### ISSUE THREAD

**Issue by telegraham** [learn-co-curriculum/sinatra-complex-forms-associations#44]
Alberto Carreras [Yesterday at 9:52 PM]
in #nyc-mhtn-web-051418
Just a heads up that this lab `https://github.com/learn-co-students/sinatra-complex-forms-associations-nyc-web-051418` is a collection of bad practices: POST for editing (does not recognize put or patch for some reason), Views with explicit class access (Pet.all instead of @pets), checkbox instead of radio for pets (selection two options could bring error)… Should be revised. (If I’m wrong in any point, please, bring it to my attention) (edited)

**Comment by drakeltheryuujin** [comment]
@sgharms @maxwellbenton there was a PR to replace `post` with `patch` that I merged in.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#46.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
