### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/sinatra-complex-forms-associations#46]
PROBLEM: MVC violations + non-RESTful routing #44
NOTIFY: @telegraham

PROBLEM: Pet belongs to an 1 owner, etc. #43
NOTIFY: @BarbaraPruz

**Comment by maxwellbenton** [comment]
PROBLEM: Solution needs extensive rebasing

**Comment by drakeltheryuujin** [comment]
Solution is out of date #68
NOTIFY: @helloamandamurphy 
@pets is not defined Curriculum #64
NOTIFY: @jmb521 #63 
use Rack::MethodOverride before mount controller #61
NOTIFY: @SamuelC28

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe these issues to have been resolved.
