### ISSUE TITLE
the code along did not help with the owner to pass all of the test

### ISSUE THREAD

**Issue by chanfe** [learn-co-curriculum/sinatra-complex-forms-associations#47]
as above

**Comment by chanfe** [comment]
I recommend updating the readme on the code along.

**Comment by chanfe** [comment]
The solution has the bug fixed but the code along the readme file did not update with the bug fix.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
