### ISSUE TITLE
Wrong grammar

### ISSUE THREAD

**Issue by cfernando415** [learn-co-curriculum/sinatra-complex-forms-associations#58]
Please check the paragraph: "This is code you should be pretty familiar with by now. We are simply creating and saving an instance of our Owner class and creating and saving two new instances of the Pet class."

**Comment by sgharms** [comment]
I'm sorry I don't see the grammatical error. I did a light sentence diagram:

```text
This is code
               that 
                  you (should be familiar with )

We are creating and saving
                        (DO) an instance of our owner class
              creating and saving
                        (DO) two new instances of the Pet class
```

This seems grammatical. Can you be more specific? Pending update we'll close this issue.
