### ISSUE TITLE
Issue with Fork

### ISSUE THREAD

**Issue by epunx2** [learn-co-curriculum/sinatra-complex-forms-associations#59]
I had an issue with many of the files showing <<<<<<< Head ======== >>>>>> with long string with numbers and letters at the end. 
views/owners/owners_controller.rb
views/owners/new.erb
views/pets/edit.erb
views/pets/new.erb
Gemfile

Also missing are some of the spec files and one of the controllers.

**Comment by drakeltheryuujin** [comment]
Hi @epunx2,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information, I'd be happy to take a second look!

As always, thanks for contributing! 💙
