### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by msherman0801** [learn-co-curriculum/sinatra-complex-forms-associations#63]
In this line: "Great! Now, we need to implement logic similar to that in our post '/owners' action to handle a user trying to associate a brand new pet to our owner:"

The "post '/owners'" should actually be "patch '/owners'".

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
