### ISSUE TITLE
@pets is not defined

### ISSUE THREAD

**Issue by jmb521** [learn-co-curriculum/sinatra-complex-forms-associations#64]
In the Owner/Edit view @pets is used, however is never defined in the controller.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#46. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
