### ISSUE TITLE
Solution is out of date

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sinatra-complex-forms-associations#68]
Hey there, 

This lab does not reflect the use of PATCH that we've been taught to use. Here's my passing solution if you want to implement any of it. It's a lot different from what's available on the current solution. 

https://github.com/helloamandamurphy/sinatra-complex-forms-associations-v-000

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for your contribution! 💙
