### ISSUE TITLE
uninitialized constant DatabaseCleaner::ActiveRecord

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-complex-forms-associations#70]
Change `gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'` to just  `gem 'database_cleaner'` to fix this issue.

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
