### ISSUE TITLE
A closed </input> tag in example

### ISSUE THREAD

**Issue by RoderickCardenas** [learn-co-curriculum/sinatra-complex-forms-associations#74]
Example:
# views/owners/new.erb
<% @pets.each do |pet| %>
  <input type="checkbox" name="owner[pet_ids][]" id="<%= pet.id %>" value="<%= pet.id %>"><%= pet.name %></input><br>
<% end %>

There is no need for a closing input tag. :)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
