### ISSUE TITLE
rake db:seed issue in Learn?

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/sinatra-complex-forms-associations#76]
Hello,

Each time I've been instructed to run ```rake db:seed``` in recent labs, I receive the following message directly below that in the terminal "/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/object/duplicable.rb:85: warning: BigDecimal.new is deprecated; use BigDecimal() method instead."

I am not sure if this is preventing the seed or not, but felt that I should share. I will ask my cohort leader about a way to tell if the seed has connected to the db.

Thanks,
Ryan

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now. When I run
`rake:db seed` I get this:
```
You have 2 pending migrations:
     1 CreateOwnersTable
     2 CreatePetsTable
Run `rake db:migrate` to update your database then try again.
```
and running `rake db:migrate` yields this:
```
== 1 CreateOwnersTable: migrating =============================================
-- create_table(:owners)
   -> 0.0006s
== 1 CreateOwnersTable: migrated (0.0007s) ====================================

== 2 CreatePetsTable: migrating ===============================================
-- create_table(:pets)
   -> 0.0005s
== 2 CreatePetsTable: migrated (0.0005s) ======================================
```
It appears that the database is seeding/migrating.
As always, thanks for contributing! 💙
